// w3_VueX/myapp/src/App.vue
<template>
  <el-container>
    <el-header>
      <el-row>
        <el-col :span="18">
          <el-menu :default-active="activeIndex" mode="horizontal" @select="handleSelect" router>
            <el-menu-item :index="item.path" v-for="item in menus" :key="item.name">
              <!-- <router-link :to="item.path"> -->
              <!-- <router-link :to="{name:item.name}"> -->
                <el-badge :value="cartlength" class="item" v-if="item.name==='cart'" style="line-height:30px">
                  {{item.text}}
                </el-badge>
                <template v-else>
                  {{item.text}}
                </template>
              <!-- </router-link> -->
            </el-menu-item>
          </el-menu>
        </el-col>
        <el-col :span="6" class="txt-right">
          <!-- <el-button-group> -->
            <el-button type="text" @click="goto('/reg')">注册</el-button>
            <el-button type="text" @click="goto('/login')">登录</el-button>
          <!-- </el-button-group> -->
        </el-col>
      </el-row>
    </el-header>
    <el-main>
      <router-view />
    </el-main>
    <el-footer>&copy;laoxie</el-footer>
  </el-container>
</template>

<script>
export default {
  name: "app",
  data() {
    return {
      activeIndex: "/home",
      menus: [
        {
          name: "home",
          path: "/home",
          text: "首页"
        },
        {
          name: "discover",
          path: "/discover",
          text: "发现"
        },
        {
          name: "cart",
          path: "/cart",
          text: "购物车"
        },
        {
          name: "mine",
          path: "/mine",
          text: "我的"
        }
      ]
    };
  },
  computed:{
    cartlength(){
      // return this.$store.state.cartlist.length;
      return this.$store.getters.cartlength
    }
  },
  methods: {
    handleSelect(index, indexpath) {
      console.log(index, indexpath);
      this.activeIndex = index;
    },
    goto(path){
      this.$router.push(path)
    }
  },
  created() {
    //获取url地址参数
    
    this.activeIndex = this.$route.path;
  },
  components: {}
};
</script>
<style lang="scss">
.current {
  color: #f00;
  font-weight: bold;
}
.txt-right{
  text-align:right;margin-top:10px
}

.price{
        del{
            &::before{
                content:'￥'
            }
        }
        >span{
            color:#f00;margin-left:5px;
            &::before{
                content:'￥'
            }
        }
    }

</style>

// w5_Redux/src/App.jsx
import React,{Component} from 'react';

import { HashRouter, 
    BrowserRouter, 
    Route, 
    Redirect, 
    Switch,
    Link,
    NavLink,
    withRouter
 } from 'react-router-dom';
import { Menu, Icon,Badge } from 'antd';
// import 'antd/dist/antd.css';


import Home from '~/Home';
import Discover from '~/Discover';
import Reg from '~/Reg';
import Login from '~/Login';
import Goods from '~/Goods/index';
import Cart from '~/Cart';

import './App.scss';

const NotFound = function () {
    return (
        <div>
            404
        </div>
    )
}

import store from '@/store';

@withRouter
class App extends Component{
    
    state = {
        selected:['/home'],
        cartlength:0,
            menu : [{
                name: 'home',
                path: '/home',
                text: '首页',
                icon: 'home'
            }, {
                name: 'discover',
                path: '/discover',
                text: '发现',
                icon: 'eye'
            }, {
                name: 'cart',
                path: '/cart',
                text: '购物车',
                icon: 'shopping-cart'
            }, {
                name: 'reg',
                path: '/reg',
                text: '注册',
                icon: 'user-add'
            }, {
                name: 'login',
                path: '/login',
                text: '登录',
                icon: 'login'
            }]
    }



    componentDidMount(){
        let {location:{pathname}} = this.props;
        let state = store.getState();
        this.setState({
            selected:[pathname],
            cartlength:state.goodslist.length
        })

        // 监听store修改，更新购物车数量
        store.subscribe(()=>{
            let state = store.getState();
            this.setState({
                cartlength:state.goodslist.length
            })
        })

    }
   
    render() {
        let {history} = this.props
        let {selected,menu,cartlength} = this.state;
        return (
            <div>
                <Menu 
                mode="horizontal"
                selectedKeys={selected}
                onSelect={({key})=>{
                    // console.log(key)
                    history.push(key)
                    this.setState({
                        selected:[key]
                    })
                }}
                theme="dark"
                >
                    {
                        menu.map(item=><Menu.Item key={item.path}>
                            {
                                item.name === 'cart' ? 
                                <Badge count={cartlength}>
                                    <Icon type={item.icon} />
                                    {item.text}
                                </Badge>
                                :
                                <React.Fragment>
                                    <Icon type={item.icon} />
                                    {item.text}
                                </React.Fragment>
                            }
                            
                        </Menu.Item>)
                    }
                    
                </Menu>
               
    
    
                <Switch>
                    <Route path="/home" component={Home} />
                    <Route path="/discover" component={Discover} />
                    <Route path="/reg" component={Reg} />
                    <Route path="/login" component={Login} />
                    <Route path="/cart" component={Cart} />
                    <Route path="/goods/:id" component={Goods} />
                    {/* <Route path="/" component={Home} exact /> */}
                    <Redirect from="/" to="/home" exact/>
                    <Route render={() => <div><h1>404</h1>页面不存在</div>} />
                </Switch>
            </div>
        )
    }
}

// App = withRouter(App)

export default App;
