// w2_VueRouter/myapp/src/pages/Home.vue
<template>
  <div>
    <el-carousel height="200px">
      <el-carousel-item v-for="item in adlist" :key="item.data">
        <img :src="item.image" style="width:100%"/>
      </el-carousel-item>
    </el-carousel>

    <div v-for="category in recommend" :key="category.title">
        <h4>{{category.title}}</h4>
        <el-row :gutter="20">
            <el-col 
            :span="6" 
            v-for="item in category.item" 
            :key="item.goods_id" 
            style="height:360px"
            @click.native="goto(item.goods_id)"
            >
                <el-image
                style="width:100%"
                :src="item.goods_image"
                fit="contain"></el-image>
                <h4>{{item.goods_name}}</h4>
                <p class="price"><del>{{item.goods_price}}</del><span>{{item.goods_promotion_price}}</span></p>
            </el-col>
        </el-row>
    </div>
  </div>
</template>
<script>
export default {
    data(){
        return {
            adlist:[],
            recommend:[]
        }
    },
  methods: {
    goto(id) {
    //   this.$router.push(`/goods/${id}`);
      this.$router.push({ name: "goods", params: { id} });
    }
  },
  async created() {
    // 发起ajax请求
    let { data:{datas} } = await this.$axios.get("https://www.nanshig.com/mobile/index.php", {
      params: {
        act: "index"
      }
    });
    
    // 轮播图数据
    this.adlist = datas[0].adv_list.item;

    // 春夏新品推荐
    this.recommend = datas.slice(1).map(item=>{
        return item.goods
    });//[{title,item},{},{},{}]
  }
};
</script>
<style lang="scss" scoped>
    
</style>

// w5_Redux/src/pages/Home.jsx
import React, { Component } from 'react';

import { Carousel,Row,Col } from 'antd';

import Api from '@/Api';

class Home extends Component {
    state = {
        recommend:[],
        datalist:[]
    }
    goto = (id)=>{
        let {history} = this.props
        history.push(`/goods/${id}`);
    }

    async componentDidMount() {
        let {datas} = await Api.get({
            act: 'index'
        });

        let recommend = datas[0].adv_list.item;

        // 格式化数据
        let datalist = datas.slice(1).map(item=>item.goods);

        this.setState({
            recommend,
            datalist
        })


    }
    render() {
        let {recommend,datalist} = this.state;
        return (
            <div>
                <Carousel>
                    {
                        recommend.map(item=>{
                            return <div>
                                <img src={item.image}  style={{width:'100%',maxHeight:160}}/>
                            </div>
                        })
                    }
                </Carousel>
                <div style={{padding:10}}>
                {
                    datalist.map(item=>{
                        return <div>
                            <h4>{item.title}</h4>
                            <Row gutter={30}>
                                {
                                    item.item.map(goods=>{
                                        return <Col 
                                        style={{minHeight:280}}
                                        xs={12}
                                        sm={6}
                                        md={4}
                                        onClick={this.goto.bind(this,goods.goods_id)}
                                        >
                                            <img src={goods.goods_image} style={{width:'100%'}}/>
                                            <h5>{goods.goods_name}</h5>
                                            <p className="price">
                                                <del>{goods.goods_price}</del>
                                                <span>{goods.goods_promotion_price}</span>
                                            </p>
                                        </Col>
                                    })
                                }
                            </Row>
                        </div>
                    })
                }
                </div>
            </div>
        )
    }
}

export default Home;
